### GET request with a header
GET http://localhost:1337/cats
Accept: application/json

### GET request with a header
GET http://localhost:1337/cats/string
Accept: application/json

### delete a cat
DELETE http://localhost:1337/cats/32

### POST request with a header
POST http://localhost:1337/cats
Content-Type: application/json

{
  "name": "string",
  "age": 0,
  "breed": "string",
  "id": "32"
}
