### loggoff
// @no-log
DELETE {{hostname}}:{{port}}/login/1337

### delete a user
// @no-log
DELETE {{hostname}}:{{port}}/user/32

### Login
// @no-log
PUT {{hostname}}:{{port}}/login
Content-Type: application/json

{
  "mail": "jcatania@ynov.com",
  "password": "marco"
}

### Login
// @no-log
PUT {{hostname}}:{{port}}/users
Content-Type: application/json

{
  "name": "Julien",
  "lastname": "Catania",
  "city": "Marseille",
  "id": 1337,
  "mail": "jcatania@ynov.com",
  "password": "marco",
  "phone": "0123456789",
  "role": "driver",
  "siret": 421337,
  "vehicule_class": "Super Driver",
  "vehicule_registration": "SE777ES",
}
